const DEFAULT_ENDPOINT = "/";

const ABOUT_ENDPOINT = "/about";
const ABOUT_UPDATE_ENDPOINT = "/about/update";

const SERVICES_ENDPOINT = "/services";
const SERVICES_ADD_ENDPOINT = "/services/add";
const SERVICES_UPDATE_ENDPOINT = "/services/update/";
const SERVICES_DELETE_ENDPOINT = "/services/delete/";

const SKILLS_ENDPOINT = "/skills";
const SKILLS_ADD_ENDPOINT = "/skills/add";
const SKILLS_UPDATE_ENDPOINT = "/skills/update/";
const SKILLS_DELETE_ENDPOINT = "/skills/delete/";

const PORTFOLIO_ENDPOINT = "/portfolio";
const PORTFOLIO_ADD_ENDPOINT = "/portfolio/add";
const PORTFOLIO_UPDATE_ENDPOINT = "/portfolio/update/";
const PORTFOLIO_DELETE_ENDPOINT = "/portfolio/delete/";

const STATISTICS_ENDPOINT = "/statistics";
const STATISTICS_UPDATE_ENDPOINT = "/statistics/update";

const CLIENTS_ENDPOINT = "/clients";
const CLIENTS_ADD_ENDPOINT = "/clients/add";
const CLIENTS_UPDATE_ENDPOINT = "/clients/update/";
const CLIENTS_DELETE_ENDPOINT = "/clients/delete/";

const SOCIALMEDIA_ENDPOINT = "/socialmedia";
const SOCIALMEDIA_ADD_ENDPOINT = "/socialmedia/add";
const SOCIALMEDIA_UPDATE_ENDPOINT = "/socialmedia/update/";
const SOCIALMEDIA_DELETE_ENDPOINT = "/socialmedia/delete/";

const CONTACT_ENDPOINT = "/contact";
const CONTACT_ADD_ENDPOINT = "/contact/add";
const CONTACT_DELETE_ENDPOINT = "/contact/delete/";

module.exports = {
    DEFAULT_ENDPOINT,
    ABOUT_ENDPOINT,
    ABOUT_UPDATE_ENDPOINT,
    SERVICES_ENDPOINT,
    SERVICES_ADD_ENDPOINT,
    SERVICES_UPDATE_ENDPOINT,
    SERVICES_DELETE_ENDPOINT,
    SKILLS_ENDPOINT,
    SKILLS_ADD_ENDPOINT,
    SKILLS_UPDATE_ENDPOINT,
    SKILLS_DELETE_ENDPOINT,
    PORTFOLIO_ENDPOINT,
    PORTFOLIO_ADD_ENDPOINT,
    PORTFOLIO_UPDATE_ENDPOINT,
    PORTFOLIO_DELETE_ENDPOINT,
    STATISTICS_ENDPOINT,
    STATISTICS_UPDATE_ENDPOINT,
    CLIENTS_ENDPOINT,
    CLIENTS_ADD_ENDPOINT,
    CLIENTS_UPDATE_ENDPOINT,
    CLIENTS_DELETE_ENDPOINT,
    SOCIALMEDIA_ENDPOINT,
    SOCIALMEDIA_ADD_ENDPOINT,
    SOCIALMEDIA_UPDATE_ENDPOINT,
    SOCIALMEDIA_DELETE_ENDPOINT,
    CONTACT_ENDPOINT,
    CONTACT_ADD_ENDPOINT,
    CONTACT_DELETE_ENDPOINT
}